web/Areas/Admin/Controllers/SocialMediaController.cs
using BLL.SocialMediaBL;
using DAL.Entities;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Helpers;

using DAL.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using web.Areas.Admin.Helpers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace web.Areas.Admin.Controllers
{
    public class SocialMediaController : Controller
    {
        //
        // GET: /Admin/SocialMedia/

        public ActionResult Index()
        {
            var list = SocialMediaManager.GetList();
            return View(list);
        }

        public ActionResult Add()
        {

           // ImageHelperNew.DestroyImageCashAndSession(1920, 1080);
            return View();
        }
        [HttpPost]
        public ActionResult Add(SocialMedia model, HttpPostedFileBase uploadfile)
        {
            //if (ModelState.IsValid)
            //{
                if (uploadfile != null && uploadfile.ContentLength > 0)
                {
                    Random random = new Random();
                    int rand = random.Next(1000, 99999999);
                    uploadfile.SaveAs(Server.MapPath("/Content/images/documents/" + Utility.SetPagePlug(model.Name) + "_" + rand + Path.GetExtension(uploadfile.FileName)));
                    model.Logo = "/Content/images/socialmedia/" + Utility.SetPagePlug(model.Name) + "_" + rand + Path.GetExtension(uploadfile.FileName);
                }
                else
                {
                    model.Logo = "Dosya Yok";
                }
                ModelState.Clear();
                ViewBag.ProcessMessage = SocialMediaManager.AddSocialMedia(model);
            //}
            return View();
        }

        public ActionResult Edit()
        {
            if (RouteData.Values["id"] != null)
            {
                int nid = 0;
                bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                if (isnumber)
                {
                    SocialMedia media = SocialMediaManager.GetSocialMediaById(nid);
                    return View(media);
                }
                else
                    return View();
            }
            else
                return View();
        }

        [HttpPost]
        public ActionResult Edit(SocialMedia media, HttpPostedFileBase uploadfile)
        {

            //if (ModelState.IsValid)
            //{
                if (uploadfile != null && uploadfile.ContentLength > 0)
                {
                    Random random = new Random();
                    int rand = random.Next(1000, 99999999);
                    new ImageHelper(280, 240).SaveThumbnail(uploadfile, "/Content/images/mediainfo/", Utility.SetPagePlug(media.Name) + "_" + rand + Path.GetExtension(uploadfile.FileName));
                    media.Logo = "/Content/images/socialmedia/" + Utility.SetPagePlug(media.Name) + "_" + rand + Path.GetExtension(uploadfile.FileName);
                }

                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        media.Id = nid;
                        ViewBag.ProcessMessage = SocialMediaManager.EditMedia(media);
                        return View(media);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(media);
                    }
                }
                else
                    return View();
            //}
            //else
            //    return View();



        }



        public JsonResult DeleteLink(int id)
        {
            bool isdelete = SocialMediaManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }


        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = SocialMediaManager.SortRecords(idsList);
            return Json(issorted);
        }

        public class JsonList
        {
            public string[] list { get; set; }

          
        }


      

    }
}

web/Areas/Admin/Views/SocialMedia/Add.cshtml
@model DAL.Entities.SocialMedia
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("_leftMenu")

<div id="page-content" class="container_12">
    <div id="page-header">
        <h2>SOSYAL MEDYA LİNKLERİ</h2>
    </div>
    @if (TempData["ImageSizeError"] != null)
    {
        <div class="notification error">@TempData["ImageSizeError"].ToString()</div>
    }
    <section class="grid_12 form">
        @Html.Hidden("ProcessMessage", (object)@ViewBag.ProcessMessage)
       @using (Html.BeginForm("Add", "SocialMedia", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
           @*  @Html.Hidden("hdfieldcategory")
            @Html.Hidden("hdfieldtaglist")*@
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Sosyal Medya Linki Ekle</legend>
                <p>
                    @Html.LabelFor(m => m.Name)
                   @Html.TextBoxFor(m => m.Name, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.Name)
                </p>

                <p>
                    @Html.LabelFor(m => m.LinkName)
                    @Html.TextBoxFor(m => m.LinkName, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.LinkName)
                </p>
              <p>
                <label for="txtname">Logo</label>
            
                <input type="file" name="uploadfile" id="uploadfile" class="required" />
            </p>
            <p>
                <label></label>
                <input type="submit" value="Kaydet" id="btnsave" />
            </p>

            </fieldset>
        }
    </section>
</div>
@section Scripts {
    <link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
    <script src="~/Areas/Admin/Content/scripts/pagescripts/banner/addbanner.js"></script>
}

web/Areas/Admin/Views/SocialMedia/Edit.cshtml
@model DAL.Entities.SocialMedia
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("_leftMenu")

<div id="page-content" class="container_12">
    <div id="page-header">
        <h2>SOSYAL MEDYA LİNKLERİ</h2>
    </div>
    @if (TempData["ImageSizeError"] != null)
    {
        <div class="notification error">@TempData["ImageSizeError"].ToString()</div>
    }
    <section class="grid_12 form">
        @Html.Hidden("ProcessMessage", (object)@ViewBag.ProcessMessage)
       @using (Html.BeginForm("Edit", "SocialMedia", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
           @*  @Html.Hidden("hdfieldcategory")
            @Html.Hidden("hdfieldtaglist")*@
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Sosyal Medya Linki Düzenle</legend>
                <p>
                    @Html.LabelFor(m => m.Name)
                   @Html.TextBoxFor(m => m.Name, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.Name)

                </p>

                <p>
                    @Html.LabelFor(m => m.LinkName)
                    @Html.TextBoxFor(m => m.LinkName, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.LinkName)
                </p>
                
              <p>
                <label for="txtname">Logo</label>
            
                <input type="file" name="uploadfile" id="uploadfile"  />
            </p>
       
                <p>
                    <label></label>
                    <input type="submit" value="Kaydet" id="btnsave" />
                </p>

            </fieldset>
        }
    </section>
</div>
@section Scripts {
    <link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
    <script src="~/Areas/Admin/Content/scripts/pagescripts/banner/addbanner.js"></script>
}

web/Areas/Admin/Views/SocialMedia/Index.cshtml
@model IEnumerable<DAL.Entities.SocialMedia>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("_leftMenu")


<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>SOSYAL MEDYA LİNKLERİ</h2>
    </div>  
    <section class="grid_12 form">
    <div class="box-header" >
        <h1>Link Listesi
            
        </h1>

    </div>
    <table id="tblcategory" class="table no-border tablesorter">
        <thead>
            <tr>
              <th class="width5">Sırala</th>
                <th class="width40">Link Adı</th>
                <th class="center witdh40">Link</th>
              
                <th class="center witdh10">İşlem</th>
            </tr>
        </thead>
         <tbody id="item-list">
            @foreach (var item in Model)
            {
               
                  <tr id="listItem_@item.Id"  class="handle">
                    <td class="center">
                        <img src="/Areas/Admin/Content/images/icons/tablesorter/arrow2.png" alt="move" border="0" class="handle sortimg" align="middle" />
                    </td>  
                    <td>
                        <span id="spanitem_@item.Id">@item.Name</span>
                        <input type="text" id="textitem_@item.Id" value="" class="displaynone textwidth90"/>
                    </td>
                    <td class="center">@item.LinkName</td>
                    <td class="center">
                       <a href="/yonetim/sosyalmedyalinkduzenle/@item.Id">
                        <img id="btn_update_@item.Id"  src="/Areas/Admin/Content/images/icons/16/edit.png"  title="Güncelle" class="cursorpointer" >
                       </a>
                       <img id="DeleteImage_@item.Id"  src="/Areas/Admin/Content/images/icons/16/delete.png" class="cursorpointer"  title="Sil" onclick="DeleteRecord('/SocialMedia/DeleteLink',@item.Id)">
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>
 <br class="cl" />
<div id="info"></div>
</div>

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>

<script src="~/Areas/Admin/Content/scripts/myscripts/SetOnlineStatusRecord.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/DeleteRecordTable.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/SortOrder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/generalprocess.js"></script>

<script src="~/Areas/Admin/Content/scripts/pagescripts/socialmedia/medialist.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/tablesorter.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/jquery.tablesorter.pager.js"></script>

web/Areas/Admin/Views/SocialMedia/_leftMenu.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">SOSYAL MEDYA LİNKLERİ</a>
<ul class="drop" style="display: block;">
     <li><a href="/yonetim/sosyalmedyalinkleri"><img src="/Areas/Admin/Content/images/icons/16/page.png">Link Listesi</a></li>
    <li><a href="/yonetim/yenilink"><img src="/Areas/Admin/Content/images/icons/16/page_add.png">Link Ekle</a></li>
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>