web/Areas/Admin/Controllers/OurTeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL.LanguageBL;
using BLL.OurTeamBL;
using DAL.Entities;
using web.Areas.Admin.Helpers;
using System.IO;
using System.Drawing;
using web.Areas.Admin.Filters;
using System.Web.Script.Serialization;
using System.Drawing.Imaging;
using web.Helpers.Enums;
using BLL.InstituionalBL;
namespace web.Areas.Admin.Controllers
{
    [AuthenticateUser]
    public class OurTeamController : Controller
    {
        
        public ActionResult Index()
        {
            string sellang = FillLanguagesList();
            var OurTeam = OurTeamManager.GetOurTeamList(sellang);
            return View(OurTeam);
        }

        public ActionResult AddOurTeam()
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            ImageHelperNew.DestroyImageCashAndSession(175, 175);
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddOurTeam(OurTeam OurTeammodel,HttpPostedFileBase uploadfile,string txtdate)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (ModelState.IsValid)
            {
                if (Session["ModifiedImageId"] != null)
                {
                    OurTeammodel.Image = "/Content/images/userfiles/" + Session["ModifiedImageId"].ToString() + Session["WorkingImageExtension"].ToString();
                    ImageHelperNew.DestroyImageCashAndSession(0,0);
                }
                else
                {
                    OurTeammodel.Image = "/Content/images/front/noimage.jpeg";
                }

                OurTeammodel.PageSlug = Utility.SetPagePlug(OurTeammodel.Name);
                OurTeammodel.TimeCreated = Utility.ControlDateTime(txtdate);
                ViewBag.ProcessMessage = OurTeamManager.AddOurTeam(OurTeammodel);
                ModelState.Clear();
                return View();
            }
            else          
                return View();
        }

        public JsonResult OurTeamEditStatus(int id)
        {
            string NowState;
            bool isupdate = OurTeamManager.UpdateStatus(id);
            return Json(isupdate);
        }

        [AllowAnonymous]
        public JsonResult DeleteOurTeam(int id)
        {
            bool isdelete = OurTeamManager.Delete(id);
            //if (isdelete)
            return Json(isdelete);
            //  else return false;
        }
        public ActionResult Danismanlarimiz()
        {
            string lang = FillLanguagesList();
            var vision_info = InstituionalManager.GetInstationalByLanguage(lang, Convert.ToInt32(EnumInstituionalTypes.Danismanlarimiz));
            return View(vision_info);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Danismanlarimiz(Institutional record)
        {
            string lang = FillLanguagesList();
            record.Language = lang;
            record.TypeId = Convert.ToInt32(EnumInstituionalTypes.Danismanlarimiz);
            ViewBag.ProcessMessage = InstituionalManager.EditInstituional(record);
            return View();
        }

        public ActionResult UzmanlikAlanlarimiz()
        {
            string lang = FillLanguagesList();
            var vision_info = InstituionalManager.GetInstationalByLanguage(lang, Convert.ToInt32(EnumInstituionalTypes.UzmanlikAlanlarimiz));
            return View(vision_info);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UzmanlikAlanlarimiz(Institutional record)
        {
            string lang = FillLanguagesList();
            record.Language = lang;
            record.TypeId = Convert.ToInt32(EnumInstituionalTypes.UzmanlikAlanlarimiz);
            ViewBag.ProcessMessage = InstituionalManager.EditInstituional(record);
            return View();
        }


        public ActionResult EditOurTeam()
        {
            ImageHelperNew.DestroyImageCashAndSession(175, 175);
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if(RouteData.Values["id"]!=null)
            {
                int nid=0;
                bool isnumber=int.TryParse(RouteData.Values["id"].ToString(),out nid);
                if (isnumber)
                {
                    OurTeam editOurTeam = OurTeamManager.GetOurTeamById(nid);
                    return View(editOurTeam);
                }
                else
                    return View();
            }
            else
                return View();
        }

        string FillLanguagesList()
        {
            string lang = "";
            if (RouteData.Values["lang"] == null)
                lang = "tr";
            else lang = RouteData.Values["lang"].ToString();

            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language", lang);
            ViewBag.LanguageList = list;
            return lang;
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditOurTeam(OurTeam OurTeammodel, HttpPostedFileBase uploadfile)
        {
            var languages = LanguageManager.GetLanguages();
            var list = new SelectList(languages, "Culture", "Language");
            ViewBag.LanguageList = list;
            if (ModelState.IsValid)
            {
         
                if (Session["ModifiedImageId"] != null)
                {
                    OurTeammodel.Image = "/Content/images/userfiles/" + Session["ModifiedImageId"].ToString() + Session["WorkingImageExtension"].ToString();
                    ImageHelperNew.DestroyImageCashAndSession(0, 0);
                }
              
                OurTeammodel.PageSlug = Utility.SetPagePlug(OurTeammodel.Name);

                if (RouteData.Values["id"] != null)
                {
                    int nid = 0;
                    bool isnumber = int.TryParse(RouteData.Values["id"].ToString(), out nid);
                    if (isnumber)
                    {
                        OurTeammodel.OurTeamId = nid;
                        ViewBag.ProcessMessage = OurTeamManager.EditOurTeam(OurTeammodel);
                        return View(OurTeammodel);
                    }
                    else
                    {
                        ViewBag.ProcessMessage = false;
                        return View(OurTeammodel);
                    }
                }

                return View();
            }
            else
                return View();
        }

        public class JsonList
        {
            public string[] list { get; set; }
        }

        public JsonResult SortRecords(string list)
        {
            JsonList psl = (new JavaScriptSerializer()).Deserialize<JsonList>(list);
            string[] idsList = psl.list;
            bool issorted = OurTeamManager.SortRecords(idsList);
            return Json(issorted);


        }

    }
}

web/Areas/Admin/Views/OurTeam/AddOurTeam.cshtml
@model DAL.Entities.OurTeam
@{
    ViewBag.Title = "AddOurTeam";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("OurTeam_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
        <h2> EKİBİMİZ</h2>
    </div>
    @if (TempData["ImageSizeError"] != null)
    {
        <div class="notification error">@TempData["ImageSizeError"].ToString()</div>
    }
    <section class="grid_12 form">
        @Html.Hidden("ProcessMessage", (object)@ViewBag.ProcessMessage)
        @using (Html.BeginForm("AddOurTeam", "OurTeam", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Hidden("hdfieldcategory")
            @Html.Hidden("hdfieldtaglist")
            @Html.ValidationSummary(true)
            <fieldset>
                <legend> Kişi Ekle</legend>
                <p>
                    @Html.Label("Dil")
                    @Html.DropDownListFor(m => m.Language, (IEnumerable<SelectListItem>)ViewBag.LanguageList, "Dil Seçiniz...")
                    @Html.ValidationMessageFor(m => m.Language)

                </p>

                <p>
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "textwidth50", Rows = "5" })
                    @Html.ValidationMessageFor(m => m.Name)
                </p>

                <p>
                    @Html.LabelFor(m => m.Linkedin)
                    @Html.TextBoxFor(m => m.Linkedin, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.Linkedin, "", new { @class = "verticalaligntop", @maxlength = 10 })
                   
                </p>
                <fieldset>
                    <legend> Resim</legend>
                    <div id="uploadPartial">
                        @Html.Partial("_imageUploadAndCrop")
                    </div>
                </fieldset>
                <p>
                    @Html.TextAreaFor(m => m.Content, new { id = "txtcontent", @class = "required" })
                    @Html.ValidationMessageFor(m => m.Content)
                </p>

                <input type="submit" value="Kaydet" id="btnsave" />

            </fieldset>
           

        }
    </section>
</div>
@section Scripts {
    <link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
    @*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
    <script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
    <script src="~/Areas/Admin/Content/scripts/pagescripts/OurTeam/addOurTeam.js"></script>


}

web/Areas/Admin/Views/OurTeam/Danismanlarimiz.cshtml
@model DAL.Entities.Institutional

@{
    ViewBag.Title = "Vizyon";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}
@*sayfa css leri*@
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />

<style>
    .cke_contents { height: auto !important;}
</style>


@Html.Partial("OurTeam_leftbar")

<div id="page-content" class="container_12">
 @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage)
       <div id="page-header">
       <h2>KURUMSAL</h2>
    </div>  
  <section class="grid_12 form">
  
    @using(Html.BeginForm())
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Danışmanlarımız</legend>
        <p>
            @Html.Label("Dil Seçimi")
            @Html.DropDownList("ddllanguage", (IEnumerable<SelectListItem>)ViewBag.LanguageList)
           
            
        </p>
        
              <br />
        <p>
            @Html.TextAreaFor(m => m.Content, new { id="txtcontent",@class="required"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <br />
      
        <p>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
    </fieldset>


    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
@*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
<script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
<script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>


<script src="~/Areas/Admin/Content/scripts/pagescripts/instituional/danismanlarimiz.js"></script>

}

web/Areas/Admin/Views/OurTeam/EditOurTeam.cshtml
@model DAL.Entities.OurTeam
@{
    ViewBag.Title = "EditOurTeam";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("OurTeam_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
        <h2>EKİBİMİZ</h2>
    </div>
    @if (TempData["ImageSizeError"] != null)
    {
        <div class="notification error">@TempData["ImageSizeError"].ToString()</div>
    }
    <section class="grid_12 form">
        @Html.Hidden("ProcessMessage", (object)@ViewBag.ProcessMessage)
        @Html.TextBoxFor(m => m.OurTeamId, new { style = "display:none;" })
        @using (Html.BeginForm("EditOurTeam", "OurTeam", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Hidden("hdfieldcategory")
            @Html.Hidden("hdfieldtaglist")
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Kişi Düzenle</legend>
                <p>
                    @Html.LabelFor(m => m.Language)
                    @Html.DropDownListFor(m => m.Language, (IEnumerable<SelectListItem>)ViewBag.LanguageList, "Dil Seçiniz...")
                    @Html.ValidationMessageFor(m => m.Language)

                </p>

                <p>
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "textwidth50", Rows = "5" })
                    @Html.ValidationMessageFor(m => m.Name)
                </p>

                <p>
                    @Html.LabelFor(m => m.Linkedin)
                    @Html.TextBoxFor(m => m.Linkedin, new { @class = "textwidth50" })
                    @Html.ValidationMessageFor(m => m.Linkedin, "", new { @class = "verticalaligntop" })

                </p>
                <fieldset>
                    <legend>Resim</legend>
                    <div id="uploadPartial">
                        @Html.Partial("_imageUploadAndCrop")
                    </div>
                </fieldset>
               @* <p>
                    <label style="line-height:25px">Resim Alt Tag'ı</label>
                    <input type="text" style="width: 50%;margin-bottom:10px" name="anaresimalttag" value="@Model.ImageTag" />
                </p>*@
                <p>
                    @Html.TextAreaFor(m => m.Content, new { id = "txtcontent", @class = "required" })
                    @Html.ValidationMessageFor(m => m.Content)
                </p>

                <br />
                <input type="submit" value="Kaydet" id="btnsave" />

            </fieldset>


        }
    </section>
</div>
@section Scripts {
    <link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
    @*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
    <script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>


    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
    <script src="~/Areas/Admin/Content/scripts/pagescripts/OurTeam/editOurTeam.js"></script>
}

web/Areas/Admin/Views/OurTeam/Index.cshtml
@model IEnumerable<DAL.Entities.OurTeam>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}
@*css dosyaları*@
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />

@Html.Partial("OurTeam_leftbar")

<div id="page-content" class="container_12">
    <div id="page-header">
       <h2>EKİBİMİZ</h2>
    </div>  
    <section class="grid_12 form">
    <div class="box-header" ><h1>Kişi Listesi
        &nbsp;&nbsp;|&nbsp;&nbsp;
             @Html.DropDownList("LanguageList")
    </h1></div>
    <table id="tblcategory" class="table no-border tablesorter">
        <thead>
            <tr>
                <th class="width5">Sırala</th>
                <th class="width50">İsim</th>
                <th class="center witdh10">Durum</th>
                <th class="center witdh10">Eklenme Tarihi</th>
                <th class="center witdh10">İşlem</th>
            </tr>
        </thead>
         <tbody id="item-list">
            @foreach (var item in Model)
            {
                <tr id="listItem_@item.OurTeamId"  class="handle">
                   <td class="center">
                        <img src="/Areas/Admin/Content/images/icons/tablesorter/arrow2.png" alt="move" border="0" class="handle sortimg" align="middle" />
                    </td>
                    <td>
                        <span id="spanitem_@item.OurTeamId">@item.Name</span>
                        <input type="text" id="textitem_@item.OurTeamId" value="" class="displaynone textwidth90"/>
                    </td>
                    <td class="center">
                        @if (item.Online == true)
                        {<img   id="img_online_@item.OurTeamId" src="/Areas/Admin/Content/images/icons/online.png" class="cursorpointer" title="Offline yap" onclick="SetOnlineStatus('/OurTeam/OurTeamEditStatus',@item.OurTeamId)" />}
                        else{<img id="img_online_@item.OurTeamId" src="/Areas/Admin/Content/images/icons/offline.png" class="cursorpointer" title="Online yap" onclick="SetOnlineStatus('/OurTeam/OurTeamEditStatus',@item.OurTeamId)" />}
                    </td>
                    <td class="center">@item.TimeCreated</td>
                    <td class="center">
                       <a href="/yonetim/ekibimizduzenle/@item.OurTeamId">
                        <img id="btn_update_@item.OurTeamId"  src="/Areas/Admin/Content/images/icons/16/edit.png"  title="Güncelle" class="cursorpointer" >
                        </a>
                        <img id="btn_save_@item.OurTeamId"  src="/Areas/Admin/Content/images/icons/16/save.png"  title="Kaydet" class="displaynone cursorpointer" onclick="UpdateRecord(@item.OurTeamId)">
                        <img id="btn_cancel_@item.OurTeamId"  src="/Areas/Admin/Content/images/icons/16/error.png"  title="İptal" class="displaynone cursorpointer" onclick="CancelRecord(@item.OurTeamId)">
                       <img id="DeleteImage_@item.OurTeamId"  src="/Areas/Admin/Content/images/icons/16/delete.png" class="cursorpointer"  title="Sil" onclick="DeleteRecord('/OurTeam/DeleteOurTeam',@item.OurTeamId)">
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>
 <br class="cl" />
<div id="info"></div>
</div>




<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/SortOrder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/generalprocess.js"></script>

<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/tablesorter.js"></script>
<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/jquery.tablesorter.pager.js"></script>
@*<script src="~/Areas/Admin/Content/scripts/plugins/tablesorter/TableSorterScript.js"></script>*@

<script src="~/Areas/Admin/Content/scripts/myscripts/SetOnlineStatusRecord.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/DeleteRecordTable.js"></script>

<script src="~/Areas/Admin/Content/scripts/pagescripts/OurTeam/OurTeamlist.js"></script>

web/Areas/Admin/Views/OurTeam/Ourteam_leftbar.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">EKİBİMİZ</a>
<ul class="drop" style="display: block;">
    <li><a href="/yonetim/ekibimiz"><img src="/Areas/Admin/Content/images/icons/16/page.png">Kişi Listesi</a></li>
    <li><a href="/yonetim/ekibimizekle"><img src="/Areas/Admin/Content/images/icons/16/page_add.png">Yeni Kişi</a></li>
    <li><a href="/yonetim/kurumsal/danismanlarimiz"><img src="/Areas/Admin/Content/images/icons/16/page.png">Danismanlarimiz</a></li>
    <li><a href="/yonetim/kurumsal/uzmanlikalanlarimiz"><img src="/Areas/Admin/Content/images/icons/16/page.png">Uzmanlik Alanlarimiz</a></li>
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>

web/Areas/Admin/Views/OurTeam/UzmanlikAlanlarimiz.cshtml
@model DAL.Entities.Institutional

@{
    ViewBag.Title = "Vizyon";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}
@*sayfa css leri*@
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />

<style>
    .cke_contents { height: auto !important;}
</style>

@Html.Partial("OurTeam_leftbar")

<div id="page-content" class="container_12">
 @Html.Hidden("ProcessMessage",(object)@ViewBag.ProcessMessage)
       <div id="page-header">
       <h2>KURUMSAL</h2>
    </div>  
  <section class="grid_12 form">
  
    @using(Html.BeginForm())
    {
         @Html.Hidden("hdfieldcategory")
         @Html.Hidden("hdfieldtaglist")
        @Html.ValidationSummary(true)
        <fieldset>
        <legend>Uzmanlık Alanlarımız</legend>
        <p>
            @Html.Label("Dil Seçimi")
            @Html.DropDownList("ddllanguage", (IEnumerable<SelectListItem>)ViewBag.LanguageList)
           
            
        </p>
        
              <br />
        <p>
            @Html.TextAreaFor(m => m.Content, new { id="txtcontent",@class="required"})
            @Html.ValidationMessageFor(m=>m.Content)
        </p>
        <br />
      
        <p>
            <input type="submit" value="Kaydet" id="btnsave" />
        </p>
    </fieldset>


    }
</section>
</div>
@section Scripts {
<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
@*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
<script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
<script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
<script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>


<script src="~/Areas/Admin/Content/scripts/pagescripts/instituional/uzmanlikalanlarimiz.js"></script>

}