web/Areas/Admin/Controllers/AnalyticController.cs
using BLL.AccountBL;
using DAL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web.Areas.Admin.Controllers
{
    public class AnalyticController : Controller
    {
        //
        // GET: /Admin/Analytic/

        public ActionResult Index()
        {
            Analytic anl = AnalyticManager.GetAnalytic();
            if (anl != null)
                return View(anl);
            else
                return View();
        }
        [ValidateInput(false)] 
        [HttpPost]
        public ActionResult Index(Analytic record)
        {
            ViewBag.Process=AnalyticManager.AddAnalytic(record.Code);
            return View(record);
        }

    }
}

web/Areas/Admin/Views/Analytic/Index.cshtml
@model DAL.Entities.Analytic
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/adminlayout.cshtml";
}

<link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/forms.css" rel="stylesheet" />
<link href="~/Areas/Admin/Content/styles/table.css" rel="stylesheet" />
@Html.Partial("_leftanalytic")

<div id="page-content" class="container_12">
    <div id="page-header">
        <h2>ANALİTİK BİLGİLERİ</h2>
    </div>
    
    <section class="grid_12 form">
        @Html.Hidden("ProcessMessage", (object)@ViewBag.ProcessMessage)
        @using (Html.BeginForm("Index", "Analytic", FormMethod.Post))
        {
            @Html.Hidden("hdfieldcategory")
            @Html.Hidden("hdfieldtaglist")
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>Google'dan almış olduğunuz kodu aşağıya yapıştırınız...</legend>
                <p>
                    @Html.TextAreaFor(m => m.Code, new { id = "_txtcontent", @class = "required", @rows = 15 })
                    @Html.ValidationMessageFor(m => m.Code)
                </p>
                <br />
               
                <br />
                <input type="submit" value="Kaydet" id="btnsave" />

            </fieldset>
           

        }
    </section>
</div>
@section Scripts {
    <link href="~/Areas/Admin/Content/styles/pluginstyles/jquery.msgbox.css" rel="stylesheet" />
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.msgbox.min.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/MessageBox.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.validate.unobtrusive.js"></script>
    @*@System.Web.Optimization.Scripts.Render("~/admin/editor")*@
    <script src="~/Areas/Admin/Content/CKEditor/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/Content/CKEditor/ckfinder/ckfinder.js"></script>
    <script src="~/Areas/Admin/Content/scripts/myscripts/CKEditorCreate.js"></script>
    <script src="~/Areas/Admin/Content/scripts/plugins/jquery.ui.datepicker-tr.js"></script>
    <script src="~/Areas/Admin/Content/scripts/pagescripts/news/addnews.js"></script>


}

web/Areas/Admin/Views/Analytic/_leftanalytic.cshtml
<aside>
<ul id="sidebar-nav"> 
<li><a href="#">GOOGLE ANALİTİK KODU</a>
<ul class="drop" style="display: block;">
    <li><a href="/yonetim/analitic"><img src="/Areas/Admin/Content/images/icons/16/page.png">Analitik Kodu </a></li>
</ul>
</li>
</ul>
<br /> <br /> 
      
</aside>